### ISSUE TITLE
Your tests need to be more robust. Test Coverage should be at least 70%

### ISSUE THREAD

**Issue by unicodeveloper** [andela-sakande/schoo#3]
<img width="969" alt="screen shot 2015-12-22 at 3 59 32 pm" src="https://cloud.githubusercontent.com/assets/2946769/11957948/1a6f0d00-a8c5-11e5-98b8-fd0b07bf5889.png">

**Comment by andela-sakande** [comment]
This issue has been resolved.


Best Regards,

*Surajudeen Akande /** Andela.com
<http://andela.com/?utm_source=andela&utm_medium=email&utm_campaign=signature> *
*Software Developer / +234-8037690966 <+234-8037690966> / @Andela
<http://bit.ly/andelatwitter>*

*"The startup that's harder to get into than Harvard" - *CNN
<http://snip.ly/HfId>
See what The Wall Street Journal <http://snip.ly/u9AI> has to say.


On Tue, Dec 22, 2015 at 4:00 PM, Prosper Otemuyiwa <notifications@github.com
