### ISSUE TITLE
Twitter authentication fails every time

### ISSUE THREAD

**Issue by unicodeveloper** [andela-sakande/schoo#4]
<img width="1121" alt="screen shot 2015-12-22 at 3 58 46 pm" src="https://cloud.githubusercontent.com/assets/2946769/11957974/39ffc68c-a8c5-11e5-8273-974dd1fc1862.png">

**Comment by andela-sakande** [comment]
All the Social Authentication routes work perfectly, I checked it on about
three different computers and there is no issue.


Best Regards,

*Surajudeen Akande*
Software Developer, *Andela*
+2348037690966 | Skype: sirolad <https://webapp.wisestamp.com/#>
<http://facebook.com/runthinz>  <http://twitter.com/babatoclean1>
<http://github.com/andela-sakande>

On Tue, Dec 22, 2015 at 4:01 PM, Prosper Otemuyiwa <notifications@github.com

**Comment by unicodeveloper** [comment]
Well, it doesnt work for me.

**Comment by andela-sakande** [comment]
This issue has been resolved.


Best Regards,

*Surajudeen Akande*
Software Developer, *Andela*
+2348037690966 | Skype: sirolad <https://webapp.wisestamp.com/#>
<http://facebook.com/runthinz>  <http://twitter.com/babatoclean1>
<http://github.com/andela-sakande>

On Tue, Dec 22, 2015 at 4:49 PM, Prosper Otemuyiwa <notifications@github.com
