### ISSUE TITLE
Wrong UI elements placement

### ISSUE THREAD

**Issue by unicodeveloper** [andela-sakande/schoo#6]
The login and Signup buttons should come before the cancel button. Here the cancel buttons appear first

<img width="1119" alt="screen shot 2015-12-22 at 3 56 14 pm" src="https://cloud.githubusercontent.com/assets/2946769/11958010/876da3d0-a8c5-11e5-8e95-4c40866e5b49.png">

<img width="1119" alt="screen shot 2015-12-22 at 3 56 35 pm" src="https://cloud.githubusercontent.com/assets/2946769/11958039/af27e8ae-a8c5-11e5-9bb1-00c4d12f878f.png">

**Comment by andela-sakande** [comment]
This issue has been resolved.


Best Regards,

*Surajudeen Akande*
Software Developer, *Andela*
+2348037690966 | Skype: sirolad <https://webapp.wisestamp.com/#>
<http://facebook.com/runthinz>  <http://twitter.com/babatoclean1>
<http://github.com/andela-sakande>

On Tue, Dec 22, 2015 at 4:05 PM, Prosper Otemuyiwa <notifications@github.com
